Este livro foi desenvolvido para a introdução do tema Computação, não
tendo a ambição de englobar toda esta vasta área do conhecimento
humano. Computação é a área responsável pelas diversas regras e
técnicas para o ato de computar, representar e disponibilizar a
informação de forma automática.

O curso de Licenciatura em Computação tem como objetivo transformar
seus egressos em profissionais que possam atuar na área da educação
com o auxílio da Computação, tanto para ensinar conceitos de sua
própria área, como também servir de consultor para professores que
atuam em diversas áreas como Matemática, História, Ciências e etc.

No entanto, para o profissional desta área se tornar um diferencial na
educação, ele precisa conhecer as Ciências da Computação, permitindo
que o mesmo possa responder a questões como: Como a informação é
representada em um computador? Como o computador realiza uma soma?
Como fazer para o computador resolver um problema específico de forma
automática? Como o computador disponibiliza informação no mundo todo e
como fazer para disponibilizar o seu material neste meio? São
perguntas como esta que o aluno irá aprender a responder durante todo
o seu curso, sendo este livro apenas um produtor de novas dúvidas.

Iremos abordar aqui a história evolutiva dos Computadores;
discutiremos sobre como a informação (números, imagem som e etc.), é
representada no computador; descreveremos a arquitetura e o
funcionamento dos componentes básicos de um computador; apresentaremos
os softwares básicos responsáveis por construir os programas
desenvolvidos por qualquer programador através de seus algoritmos;
descreveremos as funcionalidades básicas de um sistema operacional,
software que gerencia os recursos do computador e por fim
introduziremos o funcionamento das redes de computadores promovendo
comunicação instantânea entre as pessoas do mundo inteiro.

Introdução à Computação é apenas uma visão rápida sobre os diversos
temas da Computação, servindo como porta de entrada para o vasto campo
do conhecimento que vocês se aventurarão em todo o curso. Prometemos
duas coisas para quem pretende concluir este curso: muito trabalho e
muita satisfação. O educador Rubem Alves criou um belo aforismo
``Ostra Feliz não faz Pérola'', se referindo ao fato de que a ostra ao
se proteger de um corpo estranho que penetrou em sua concha, cria uma
defesa natural ao redor deste invasor, gerando por fim uma pérola,
entretanto, durante este processo a ostra sofre muito devido à falta
de defesa dentro de sua concha. Para nós aprendizes o ensino é assim,
cheio de sofrimento, mas ao final teremos criado nossas próprias
pérolas.

=== Público alvo

O público alvo desse livro são os alunos de Licenciatura em
Computação, na modalidade à distância footnote::[Embora ele tenha sido
feito para atender aos alunos da Universidade Federal da Paraíba, o
seu uso não se restringe a esta  universidade, podendo ser adotado por
outras universidades do sistema UAB.]. Ele foi concebido para ser
utilizado numa disciplina de 'Introdução à Computação', no primeiro
semestre do curso.

[[como_estudar]]
=== Como você deve estudar cada capítulo

* Leia a visão geral do capítulo
* Estude os conteúdos das seções
* Realize as atividades no final do capítulo
* Verifique se você atingiu os objetivos do capítulo

.Na sala de aula do curso
* Tire dúvidas e discuta sobre as atividades do livro com outros integrantes do curso
* Leia materiais complementares eventualmente disponibilizados
* Realize as atividades propostas pelo professor da disciplina


////
Sempre terminar o arquivo com uma nova linha.
////

